### ISSUE TITLE
Segmentation violation while io.Copy to nil Writer

### ISSUE THREAD

**Issue by movsb** [alibaba/kt-connect#253]
**Describe the bug**

The following code will cause a segmentation violation since its underlying writer was passed nil:

https://github.com/alibaba/kt-connect/blob/e706f8df271cf671b551a211270f38e26db06869/pkg/kt/exec/sshuttle/commands.go#L45-L48

Here is the log:

```-
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a9e02]

goroutine 100 [running]:
bufio.(*Writer).Flush(0xc00003b880, 0xc0003eeff1, 0xf)
        /opt/hostedtoolcache/go/1.15.15/x64/src/bufio/bufio.go:607 +0x62
bufio.(*Writer).ReadFrom(0xc00003b880, 0x174b7e0, 0xc0003a00c0, 0x7fb7d0f96be0, 0xc00003b880, 0x1000200000001)
        /opt/hostedtoolcache/go/1.15.15/x64/src/bufio/bufio.go:738 +0x2a5
io.copyBuffer(0x1749ae0, 0xc00003b880, 0x174b7e0, 0xc0003a00c0, 0x0, 0x0, 0x0, 0x43f916, 0x1658e88, 0x0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/io/io.go:395 +0x2ff
io.Copy(0x1749ae0, 0xc00003b880, 0x174b7e0, 0xc0003a00c0, 0x9, 0x1c, 0x463a00)
        /opt/hostedtoolcache/go/1.15.15/x64/src/io/io.go:368 +0x5a
created by github.com/alibaba/kt-connect/pkg/kt/exec/sshuttle.(*Cli).Connect
        /home/runner/work/kt-connect/kt-connect/pkg/kt/exec/sshuttle/commands.go:47 +0x56a
```

Changing `bufio.NewWriter(nil)` to `ioutil.Discard` fixes this.

**Log**
please add -d to debug log

**Environment (please complete the following information):**

Doesn't matter.

**Additional context**

**Comment by linfan** [comment]
Thanks @xyz-li
