### ISSUE TITLE
connect模式请问不支持dubbo3+nacos2吗?

### ISSUE THREAD

**Issue by ilaotan** [alibaba/kt-connect#273]
**Describe the bug**

如题,调研阶段,发现没法本地把服务注册到k8s集群内部的nacos.同项目直接连该nacos外网ip是正常的.
ktctl -d -n dev connect 
spring-dubbo项目启动添加参数  -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=2223
kt开启debug模式.能打印一堆连接到2223信息.

**Log**
```
Caused by: org.apache.dubbo.rpc.RpcException: Failed to register dubbo://172.32.4.247:20880/com.xxx.interfaces.IDemoService?anyhost=true&application=dubbo-provider-demo&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ilaotan.interfaces.IDemoService&metadata-type=remote&methods=sayHello,sayHello2&pid=2136&release=3.0.5&revision=1.0.0&service-name-mapping=true&side=provider&status=server&timestamp=1643274727550&version=1.0.0 to nacos nacos://10.233.51.59:8848/org.apache.dubbo.registry.RegistryService?application=dubbo-provider-demo&dubbo=2.0.2&file=/root/.dubbo/dubbo-provider-demo&group=dubbo&interface=org.apache.dubbo.registry.RegistryService&pid=2136&qos.enable=false&release=3.0.5, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:180) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-3.0.5.jar:3.0.5]
	... 36 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar:na]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:59) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:177) ~[dubbo-3.0.5.jar:3.0.5]
	... 37 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:635) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:269) ~[nacos-client-2.0.3.jar:na]
	... 43 common frames omitted
```

**Environment (please complete the following information):**
windows10
dubbo 3.0.5
nacos 2.0.3
kt  0.2.5

**Additional context**

**Comment by ilaotan** [comment]
棒,使用0.3可以了.
