### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by flypolarbear** [alibaba/kt-connect#285]
**Describe the bug**

在执行ktctl connect 的时候遇到该错误
![image](https://user-images.githubusercontent.com/49713432/157732490-4ad04c2d-6fba-46a1-b833-fdda4f15c59e.png)

**Log**

```
PS C:\Windows\system32> ktctl connect
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x1503008]

goroutine 1 [running]:
github.com/alibaba/kt-connect/pkg/kt/command/general.CombineKubeOpts()
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/general/setup.go:45 +0x628
github.com/alibaba/kt-connect/pkg/kt/command.NewConnectCommand.func1(0xc0003e4840)
        /home/runner/work/kt-connect/kt-connect/pkg/kt/command/connect.go:27 +0x217
github.com/urfave/cli.HandleAction({0x17e2b40, 0xc0003e0620}, 0x7)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0xa8
github.com/urfave/cli.Command.Run({{0x1aab1ca, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1ae505d, 0x2d}, {0x1ace6c9, ...}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x652
github.com/urfave/cli.(*App).Run(0xc000320a80, {0xc0001223a0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x80c
main.main()
        /home/runner/work/kt-connect/kt-connect/cmd/ktctl/main.go:46 +0x5d7
```

**Environment (please complete the following information):**
 - Mac M1 /win11
 - Kubernetes [1.20.1]
 - KT Version [0.3.1]

**Comment by linfan** [comment]
暂时无法复现，下个版本会根据堆栈尝试做一下兜底异常处理

**Comment by linfan** [comment]
从报错的位置来看，是在解析 kube config 文件的时候遇到了非预期的内容，但从堆栈本身看不出具体导致报错的原因。
如果可能的话，能否提供一下本地 ${HOME}/.kube/config 这个文件的内容呢？（可以把其中的IP地址和鉴权秘钥内容用占位符替代脱敏）

**Comment by linfan** [comment]
0.3.3 版本增加了配置有效性的检查，请验证。
如果问题依然出现，麻烦提供一个可复现的 kubeconfg 配置文件，并重新打开这个issue，谢谢
