### ISSUE TITLE
connect already running，but no pod found

### ISSUE THREAD

**Issue by BinchenQ** [alibaba/kt-connect#37]
**Describe the bug**
when i run ktctl -n commece connect ,I get an error as bellow,
but no pod running in this namespace,and the kt-dashboard has 0 connect ,
how can i clean this process ?

**Log**
please add -d to debug log
$ ktctl -n commerce connect
panic: Connect already running. exit this

goroutine 1 [running]:
gitlab.alibaba-inc.com/rdc-incubator/kt/pkg/kt/action.(*Action).Connect(0xc420159700, 0x8ae, 0x10adf00, 0x0, 0x0)
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/pkg/kt/action/ConectAction.go:19 +0x62f
main.main.func1(0xc4202a0160, 0xc42028e500, 0xc4202a0160)
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/cmd/standalone/main.go:106 +0x114
gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli.HandleAction(0xf4cc20, 0xc42026e3c0, 0xc4202a0160, 0x0, 0xc42028e5a0)
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli/app.go:502 +0xbe
gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli.Command.Run(0x10aecdd, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10c254a, 0x20, 0x0, ...)
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli/command.go:165 +0x47d
gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli.(*App).Run(0xc420094fc0, 0xc4200a8000, 0x4, 0x4, 0x0, 0x0)
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/vendor/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
	/Users/yunlong/go/src/gitlab.alibaba-inc.com/rdc-incubator/kt/cmd/standalone/main.go:158 +0xcb9

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 14.04]
 - Kubernetes [e.g. 1.10.1]
 - KT Version [e.g. 0.0.4]

**Additional context**

**Comment by BinchenQ** [comment]
remove the pid file in ~/.ktctl ,it works
